Feat/dark mode
ingcarlostello/appyenda pull request #31
Opened 2024-04-20 06:32 UTC by emmanuelgaravito

Added Dark Mode functionality.

2024-04-20 23:39 UTC, ingcarlostello requested changes

2024-04-20 23:39 UTC, ingcarlostello commented on app/[locale]/(auth)/layout.tsx
> +		<main className=" ">
if there are no classes remove className

2024-04-20 23:39 UTC, ingcarlostello commented on app/[locale]/dashboard/layout.tsx
> +				<div className="  w-2/12 border-r h-screen max-[767px]:hidden md:block md:w-1/4 lg:w-1/6">
delete space

2024-04-20 23:39 UTC, ingcarlostello commented on app/[locale]/dashboard/profile/page.tsx
> +					<div className=" md:w-3/6 lg:w-3/6 xl:w-2/4 p-8 flex flex-col gap-10">
delete space

2024-04-22 16:20 UTC, emmanuelgaravito commented on app/[locale]/(auth)/layout.tsx
> +		<main className=" ">
Done

2024-04-22 16:21 UTC, emmanuelgaravito commented on app/[locale]/dashboard/layout.tsx
> +				<div className="  w-2/12 border-r h-screen max-[767px]:hidden md:block md:w-1/4 lg:w-1/6">
Done

2024-04-22 16:22 UTC, emmanuelgaravito commented on app/[locale]/dashboard/profile/page.tsx
> +					<div className=" md:w-3/6 lg:w-3/6 xl:w-2/4 p-8 flex flex-col gap-10">
Done

2024-04-22 17:13 UTC, ingcarlostello approved these changes

2024-04-22 17:13 UTC, merged